name: Parallel Workflow with Matrix and JSON

on:
  push:
    branches: [main]

jobs:
  job-group-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [8, 10, 12]
        group: [group1, group2, group3]
        include:
          - os: ${{ matrix.os }}
            version: ${{ matrix.version }}
            group: ${{ matrix.group }}
            run_job: ${{ fromJSON(needs.json-data.outputs.conditions)[matrix.group] }}
    needs: json-data
    steps:
      - name: Step 1
        if: matrix.run_job == 'true'
        run: echo "Job in Group 1 with OS ${{ matrix.os }}, Version ${{ matrix.version }}"
      - name: Step 2
        if: matrix.run_job == 'true'
        run: echo "Group 1 Job finished with OS ${{ matrix.os }}, Version ${{ matrix.version }}"

  job-group-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [8, 10, 12]
        group: [group1, group2, group3]
        include:
          - os: ${{ matrix.os }}
            version: ${{ matrix.version }}
            group: ${{ matrix.group }}
            run_job: ${{ fromJSON(needs.json-data.outputs.conditions)[matrix.group] }}
    needs: json-data
    steps:
      - name: Step 1
        if: matrix.run_job == 'true'
        run: echo "Job in Group 2 with OS ${{ matrix.os }}, Version ${{ matrix.version }}"
      - name: Step 2
        if: matrix.run_job == 'true'
        run: echo "Group 2 Job finished with OS ${{ matrix.os }}, Version ${{ matrix.version }}"

  job-group-3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [8, 10, 12]
        group: [group1, group2, group3]
        include:
          - os: ${{ matrix.os }}
            version: ${{ matrix.version }}
            group: ${{ matrix.group }}
            run_job: ${{ fromJSON(needs.json-data.outputs.conditions)[matrix.group] }}
    needs: json-data
    steps:
      - name: Step 1
        if: matrix.run_job == 'true'
        run: echo "Job in Group 3 with OS ${{ matrix.os }}, Version ${{ matrix.version }}"
      - name: Step 2
        if: matrix.run_job == 'true'
        run: echo "Group 3 Job finished with OS ${{ matrix.os }}, Version ${{ matrix.version }}"

  json-data:
    runs-on: ubuntu-latest
    steps:
      - name: Read JSON file
        uses: actions/github-script@v4
        with:
          script: |
            const data = require('./repos.json');
            console.log(JSON.stringify({ conditions: data.conditions }));
          writeFile: |
            ./output.json
        id: write-json
      - name: Read JSON output
        id: read-json
        uses: actions/github-script@v4
        with:
          script: |
            const content = require('./output.json');
            console.log(JSON.stringify(content));
          result-encoding: string
      - name: Output JSON variables
        run: echo "${{ steps.read-json.outputs.result }}"
        id: json-data
