name: Parallel Jobs Workflow

on: [push]

jobs:
  group1:
    name: Group 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [job_1_v1, job_2_v1, job_3_v1, job_4_v1, job_5_v1, job_6_v1, job_7_v1, job_8_v1, job_9_v1, job_10_v1]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run Job
      if: ${{ fromJson(file('./job_conditions.json')).conditions.group1[ matrix.job ] }}
      run: echo "Running Job ${{ matrix.job }} for Group 1"
      # Add additional steps for job_1_v1, job_2_v1, etc. as needed
      
  group2:
    name: Group 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [job_1_v2, job_2_v2, job_3_v2, job_4_v2, job_5_v2, job_6_v2, job_7_v2, job_8_v2, job_9_v2, job_10_v2]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run Job
      if: ${{ fromJson(file('./job_conditions.json')).conditions.group2[ matrix.job ] }}
      run: echo "Running Job ${{ matrix.job }} for Group 2"
      # Add additional steps for job_1_v2, job_2_v2, etc. as needed
