name: Extract variables and run jobs

on:
  push:
    branches: [main]

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: JSON to variables
      uses: rgarcia-phi/json-to-variables@v1.1.0
      with:
        filename: 'repos.json'
        prefix: test
        masked: true
    - name: Show output
      run: echo "The time was ${{ env.test_value }}, ${{ env.test_array_0_value }}, ${{ env.test_obj_value1 }}"
    - name: Show output details
      run: |
        echo job1 valuse : ${{ env.test_job1_value }}
        echo job2 valuse : ${{ env.test_job2_value }}
        echo job3 valuse : ${{ env.test_job3_value }}
        echo job4 valuse : ${{ env.test_job4_value }}
    


