name: Extract variables and run jobs

on:
  push:
    branches: [main]

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Extract variables from JSON
      id: extract-variables
      run: |
        export MY_JSON_FILE=repos.json
        export KEYS=$(jq -r 'keys[]' $MY_JSON_FILE)
        for KEY in $KEYS; do
          export VALUE=$(jq -r ".$KEY" $MY_JSON_FILE)
          echo "Setting $KEY=$VALUE as environment variable"
          env | grep $KEY || export $KEY="$VALUE"
        done

    - name: Use extracted variables
      run: |
        echo "Variable1: $job1"
        echo "Variable2: $job2"
        echo "Variable3: $job3"

