name: Extract variables and run jobs

on:
  push:
    branches: [main]

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: JSON to variables
      uses: rgarcia-phi/json-to-variables@v1.1.0
      with:
        filename: 'repos.json'
        prefix: 'webmule'
        masked: false
    - name: Show output details
      run: |
        echo job1 valuse : ${{ env.webmule_job1-sys-api }}
        echo job2 valuse : ${{ env.webmule_job2-sys-api }}
        echo job3 valuse : ${{ env.webmule_job3-sys-api }}
        echo job4 valuse : ${{ env.webmule_job4-sys-api }}
    
    - name: Show output details job1
      if: env.webmule_job1-sys-api == 'true'
      run: |
        echo job1 valuse : ${{ env.webmule_job1-sys-api }}

    - name: Show output details job2
      if: env.webmule_job2-sys-api == 'true'
      run: |
        echo job2 valuse : ${{ env.webmule_job2-sys-api }}
    - name: Show output details job3
      if: env.webmule_job3-sys-api == 'true'
      run: |
        echo job3 valuse : ${{ env.webmule_job3-sys-api }}        
