name: Parallel Jobs with Matrix Strategy

on:
  push:
    branches:
      - develop


jobs:
  group-1:
    strategy:
      matrix:
        group: [1, 2, 3]
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Group 1, Variable ${{ matrix.group }} Step 1"
      - name: Step 2
        run: echo "Group 1, Variable ${{ matrix.group }} Step 2"

  group-2:
    strategy:
      matrix:
        group: [4, 5, 6]
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Group 2, Variable ${{ matrix.group }} Step 1"
      - name: Step 2
        run: echo "Group 2, Variable ${{ matrix.group }} Step 2"

  group-3:
    strategy:
      matrix:
        group: [7, 8, 9]
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Group 3, Variable ${{ matrix.group }} Step 1"
      - name: Step 2
        run: echo "Group 3, Variable ${{ matrix.group }} Step 2"
